### PR TITLE
Added readme

### PR DESCRIPTION
**Pull request by buckspencer**

### CODE REVIEW

**Comment by jah2488** [comment]
I think something went wrong with your pull request. This is asking to merge the `jacob` branch into `master`

Lets try again.

**Comment by buckspencer** [comment]
it doesn't want me making a pull request

On Thu, Feb 19, 2015 at 6:10 PM, Justin Herrick notifications@github.com
wrote:

> I think something went wrong with your pull request. This is asking to
> merge the jacob branch into master
> 
> Lets try again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tiy-austin-ror-jan2015/tiy-rails-template/pull/32#issuecomment-75166271
> .

## 

-Buck Spencer

**Comment by jah2488** [comment]
@buckspencer You can start the pull request on your fork of the repo. I went ahead and did it for you. _see below_

pr_setup

**Comment by buckspencer** [comment]
very nifty

On Thu, Feb 19, 2015 at 6:33 PM, Justin Herrick notifications@github.com
wrote:

> @buckspencer https://github.com/buckspencer You can start the pull
> request on your fork of the repo. I went ahead and did it for you. _see
> below_
> 
> [image: pr_setup]
> https://cloud.githubusercontent.com/assets/249209/6279342/bce9526c-b865-11e4-89e7-c76b771803f6.gif
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tiy-austin-ror-jan2015/tiy-rails-template/pull/32#issuecomment-75168742
> .

## 

-Buck Spencer

**Pull request closed without merging**
